### ISSUE TITLE
Improvement suggestion: add LLDPd

### ISSUE THREAD

**Issue by jdaandersj** [mib1185/ha-addon-snmpd#10]
Hi, nice add-on, it works well with SNMP.

Would it be possible to add lldpd running with the flag -x?
Then we would also get layer 2 info exposed over SNMP.

I can provide more detail if you are not familiar with lldpd.

Thanks

**Comment by mib1185** [comment]
Hi @jdaandersj 
I like this idea, please feel free to test the linked PR if there is something missing, thx :+1:

**Comment by jdaandersj** [comment]
Thanks, looks good. I only made one small comment that's not really important on the PR.

One thing I thought: lots of people like to also enable some of CDP/FDP/EDP/SONMP options of LLDP (-c -f -e -s). CDP is very popular. I don't really mind, what you've already done is all I was trying to achieve but maybe those are nice options too?

Thank you for fast response :)

**Comment by mib1185** [comment]
Let's us start with LLDP only and if users asks for these proprietary discovery protocols, then they could still be added

**Comment by mib1185** [comment]
btw the new version is now available

**Comment by jdaandersj** [comment]
Very nice, updated already and works good
