### ISSUE TITLE
unexpected header length in /proc/net/snmp. 237 != 224

### ISSUE THREAD

**Issue by forwardcomputers** [mib1185/ha-addon-snmpd#12]
Hi,

Getting a continuous error message on the console.
  `snmpd[144]: systemstats_linux: unexpected header length in /proc/net/snmp. 237 != 224`

There is a Debian's bug report on this that I found
  [https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1069087](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1069087)

**Comment by mib1185** [comment]
Hi @forwardcomputers 
Thanks for this report. I'm already aware of this issue and that fix in https://github.com/net-snmp/net-snmp/pull/785. But there is no release of snmpd yet containing this fix, so we need to wait

**Comment by forwardcomputers** [comment]
Thanks for the update.

**Comment by vincesmits** [comment]
When expect the update for this?

**Comment by mib1185** [comment]
As this is an issue in the net-snmp tool, we still need to wait for an update of this (_see also my comment above_). But it seems that they're preparing a new [release 5.10](https://github.com/net-snmp/net-snmp/tags). Let's see how long it will take for the final version

**Comment by mib1185** [comment]
This is fixed in [v0.5.0](https://github.com/mib1185/ha-addon-snmpd/releases/tag/v0.5.0)
