### ISSUE TITLE
Setting up the SNMP

### ISSUE THREAD

**Issue by pq16** [mib1185/ha-addon-snmpd#14]
Hello. I can't understand how to configure the sensor in the HA for transmission via SNPM. Where is the configuration created? I need to transmit the temperature value from the sensor from the HA. I would be very grateful if you show me an example. Thank you.

**Comment by mib1185** [comment]
Hi @pq16 
this add-on does not create any sensors or entities in HA itself, but it makes system data available to be fetched via SNMP protocol from your HA. The configuration of this add-on is located in HA under Settings -> Add-ons -> SNMPD

**Comment by pq16** [comment]
Yes, I understand that the addon does not collect sensors. I need to transfer data from the XA (sensor.0xa4c138b9aa6b0a6c_temperature) according to the protocol SNMP. Where should I specify what data to send according 
The addon configuration contains the following linesж:
snmp_community: pmnsssah
snmp_name: ha
snmp_location: home
snmp_contact: me
lldp_enabled: false

**Comment by mib1185** [comment]
ah, now I get it - at the moment, there is no option to expose any HA entities via SNMP. This add-on uses the system provided data - in case of temperature, read here #2
