### ISSUE TITLE
Temperature

### ISSUE THREAD

**Issue by thetravellor** [mib1185/ha-addon-snmpd#2]
Hi, love it! I have it working with check_mk

Is there any way to get it to pull the temperature of the device out?

**Comment by mib1185** [comment]
HI @thetravellor 
it depends on your hardware, for my test pi you will find the temperature sensors in the [lmTempSensorsTable](http://www.circitor.fr/Mibs/Html/L/LM-SENSORS-MIB.php#lmTempSensorsTable) (_oid .1.3.6.1.4.1.2021.13.16.2_)
