### ISSUE TITLE
How to configure community string

### ISSUE THREAD

**Issue by ElGato** [mib1185/ha-addon-snmpd#7]
Unable to connect to default community, assuming public.

*edit: OK found the default community string, but is it possible to update, along with other information, such as contact, location etc...

**Comment by mib1185** [comment]
Hi @ElGato 
you should find these information in the add-on docs

**Comment by ElGato** [comment]
> Hi @ElGato you should find these information in the add-on docs

Thank you, I found the DOCS but it is not clear to me how to change the information.

**Comment by mib1185** [comment]
you can change these on the configuration tab of the add-on in HA

**Comment by ElGato** [comment]
> you can change these on the configuration tab of the add-on in HA

Thank you. DOH! Completely missed that. Still new to HA and was surprised to find it didn't natively support SNMP so thank you for this. Case closed

**Comment by ElGato** [comment]
> you can change these on the configuration tab of the add-on in HA

Thank you. DOH! Completely missed that. Still new to HA and was surprised to find it didn't natively support SNMP so thank you for this. Case closed
