### ISSUE TITLE
Unable to install after adding repository

### ISSUE THREAD

**Issue by bob-gorman** [mib1185/ha-addon-snmpd#8]
**I get the following when I try to install:** 

Failed to install add-on
The command '/bin/bash -o pipefail -c apt-get update && apt-get install -y snmpd && apt-get clean autoclean && apt-get autoremove -y' returned a non-zero code: 100

**My System - I just updated everything, perhaps there was a breaking change?** 
- Core: 2024.3.1
- Supervisor: 2024.03.0
- Operating System: 12.1
- Frontend: 20240307.0

**Comment by mib1185** [comment]
Hi @bob-gorman 
could you please provide the supervisor log (_settings->systems->logs->"select supervisor on the top right"_) and the [diagnostics](https://www.home-assistant.io/integrations/diagnostics) information of the have integration?

Note: it is better to drag the log into the comment (_which will add it as an attachment_) and not copy paste as it is hard to read logs in GitHub.

Btw. Which board/hardware do you use?

thx 👍

**Comment by bob-gorman** [comment]
@mib1185 
Thank you for the quick response. 

I am on Raspi4 4GB. The integration has not yet installed correctly, so I do not have diagnostics, unless there is another way to get to it. 

The log errors on resolving deb.debian.org, so I ran nslookup. It finds it in a cname reference. 
Server:		127.0.0.11
Address:	127.0.0.11#53

Non-authoritative answer:
deb.debian.org	canonical name = debian.map.fastlydns.net.
Name:	debian.map.fastlydns.net
Address: 199.232.98.132
Name:	debian.map.fastlydns.net
Address: 2a04:4e42:58::644

here is the output from the superviser log

[supervisor-log.txt](https://github.com/mib1185/ha-addon-snmpd/files/14628784/supervisor-log.txt)

**Comment by mib1185** [comment]
"where" did you run the nslookup - it should be run on the HA OS cli directly and also within the Terminal add-on or directly on the homeassistant core docker container (_if you know how_)

**Comment by mib1185** [comment]
> The integration has not yet installed correctly

if hacs is not installed, how did you add this repository to your HA instance?

**Comment by bob-gorman** [comment]
nslookup via terminal add-on. 

Hacs is installed, but I could not find anything for snmpd. So, I followed the directions on the bottom of the GIT page. 

"Or navigate to Settings -> Add-ons -> Add-on store -> 3 dots top right corner -> Repositories than add https://github.com/mib1185/ha-addon-snmpd as new repository."

**Comment by mib1185** [comment]
> and the [diagnostics](https://www.home-assistant.io/integrations/diagnostics) information of the have integration?

ok, than this should be possible?

---

just to make sure, did you already restarted everything? do you use a pihole or adguard (_or anything like a DNS "filter" system_) on your network?

**Comment by bob-gorman** [comment]
I do work in IT... so reboot is step on when troubleshooting. 
I do run AdGuard, but it is not blocking anything... out bound. 
I can use curl http://deb.debian.org/debian/dists/bookworm/InRelease and I get a list of files back

**Comment by mib1185** [comment]
> I do work in IT... so reboot is step on when troubleshooting.

perfect 😁 👍 

> I can use curl http://deb.debian.org/debian/dists/bookworm/InRelease and I get a list of files back

Please try this directly on the console of your PI, also the DNS test

**Comment by bob-gorman** [comment]
Pi is headless running ha os

**Comment by mib1185** [comment]
you can enable ssh on port 22222 on the HAOS as described [here](https://developers.home-assistant.io/docs/operating-system/debugging/#home-assistant-operating-system)
